// Code generated by MockGen. DO NOT EDIT.
// Source: notifier.go
//
// Generated by this command:
//
//	mockgen -source=notifier.go -destination=mock_notifier.go -package=notify
//

// Package notify is a generated GoMock package.
package notify

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
	isgomock struct{}
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// Fail mocks base method.
func (m *MockNotifier) Fail(site, message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Fail", site, message)
}

// Fail indicates an expected call of Fail.
func (mr *MockNotifierMockRecorder) Fail(site, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fail", reflect.TypeOf((*MockNotifier)(nil).Fail), site, message)
}

// Success mocks base method.
func (m *MockNotifier) Success(site, message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Success", site, message)
}

// Success indicates an expected call of Success.
func (mr *MockNotifierMockRecorder) Success(site, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Success", reflect.TypeOf((*MockNotifier)(nil).Success), site, message)
}
