// Code generated by MockGen. DO NOT EDIT.
// Source: smtp.go
//
// Generated by this command:
//
//	mockgen -source=smtp.go -destination=mock_smtp.go -package=notify
//

// Package notify is a generated GoMock package.
package notify

import (
	context "context"
	reflect "reflect"

	"github.com/kias-hack/isp-site-checker/internal/util"
	gomock "go.uber.org/mock/gomock"
)

// MockMailSender is a mock of MailSender interface.
type MockMailSender struct {
	ctrl     *gomock.Controller
	recorder *MockMailSenderMockRecorder
	isgomock struct{}
}

// MockMailSenderMockRecorder is the mock recorder for MockMailSender.
type MockMailSenderMockRecorder struct {
	mock *MockMailSender
}

// NewMockMailSender creates a new mock instance.
func NewMockMailSender(ctrl *gomock.Controller) *MockMailSender {
	mock := &MockMailSender{ctrl: ctrl}
	mock.recorder = &MockMailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailSender) EXPECT() *MockMailSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockMailSender) Send(ctx context.Context, mail *util.Mail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, mail)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockMailSenderMockRecorder) Send(ctx, mail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMailSender)(nil).Send), ctx, mail)
}
