// Code generated by MockGen. DO NOT EDIT.
// Source: internal/checker/checker.go
//
// Generated by this command:
//
//	mockgen -source=internal/checker/checker.go -destination=internal/checker/mock_sender.go -package=checker
//

// Package checker is a generated GoMock package.
package checker

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotificationSender is a mock of NotificationSender interface.
type MockNotificationSender struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationSenderMockRecorder
	isgomock struct{}
}

// MockNotificationSenderMockRecorder is the mock recorder for MockNotificationSender.
type MockNotificationSenderMockRecorder struct {
	mock *MockNotificationSender
}

// NewMockNotificationSender creates a new mock instance.
func NewMockNotificationSender(ctrl *gomock.Controller) *MockNotificationSender {
	mock := &MockNotificationSender{ctrl: ctrl}
	mock.recorder = &MockNotificationSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationSender) EXPECT() *MockNotificationSenderMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockNotificationSender) Error(domain, result string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", domain, result)
}

// Error indicates an expected call of Error.
func (mr *MockNotificationSenderMockRecorder) Error(domain, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockNotificationSender)(nil).Error), domain, result)
}

// Send mocks base method.
func (m *MockNotificationSender) Send(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockNotificationSenderMockRecorder) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockNotificationSender)(nil).Send), arg0)
}

// Success mocks base method.
func (m *MockNotificationSender) Success(domain string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Success", domain)
}

// Success indicates an expected call of Success.
func (mr *MockNotificationSenderMockRecorder) Success(domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Success", reflect.TypeOf((*MockNotificationSender)(nil).Success), domain)
}
